### ISSUE TITLE
Starting dose-symmetric from non-zero PreTilt Angle

### ISSUE THREAD

**Issue by dgvjay** [alberttxu/FastTomo#1]
Great work and congratulations on the FastTomo

I work with FIBbed lamellae that have a non-zero PreTilt of 7-13 degrees, so we do dose-symmetric from this non-zero PreTilt.  In my perusal of the instructions and the script, it seems, currently, the dose-symmetric can only be run from 0 degree tilt. Is my interpretation correct? 

Thanks and cheers

**Comment by alberttxu** [comment]
Hi @dgvjay, thanks for the suggestion. Currently I have an implementation with a non-zero starting angle, but need to fully test it before committing. Good to know that it's something people want. Hopefully I will be able to make the commit in the next week or so.

**Comment by dgvjay** [comment]
Thank you!
